name: Build & Test with modules

on: 
    push:   
        branches:
        - main
    pull_request:
        branches:
        - main
    workflow_dispatch:
    release:
        types: [published]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.runs_on }}-${{ matrix.compiler }}-${{ matrix.configure_preset }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs_on: windows-2025-vs2026
            compiler: msvc-14.50
            configure_preset: "x64-vs"
            build_preset: "x64-vs-build"
            test_preset : "x64-vs-test"
          - runs_on: ubuntu-26.04
            compiler: gcc-15
            cc: gcc-15
            cxx: g++-15
            configure_preset: "linux"
            build_preset: "linux-build"
            test_preset : "linux-test"
          - runs_on: ubuntu-26.04
            compiler: clang-22
            cc: clang-22
            cxx: clang++-22
            configure_preset: "linux"
            build_preset: "linux-build"
            test_preset : "linux-test"
    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: lukka/get-cmake@4a7d025fc60f00db0c7b44ebf783d19b52444830 # v4.4.1

    - name: "Build & Test"
      uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956 # v10.9
      env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
      with:
        configurePreset: ${{ matrix.configure_preset }}
        configurePresetAdditionalArgs: "['-DUT_ENABLE_MODULES=ON']"
        buildPreset: ${{ matrix.build_preset }}
        testPreset: ${{ matrix.test_preset }}
